version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    command: sh -c "./entrypoint.sh"
    volumes:
      - .:/app
    restart: on-failure
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      POOL_SIZE: ${POOL_SIZE}
      PORT: ${PORT}
    ports:
      - "4000:${PORT}"
    networks:
      - phx_net
    depends_on:
      - db_service

  db_service:
    image: postgres:alpine
    container_name: ${POSTGRES_HOST}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5430:${POSTGRES_PORT}"
      # volumes:
      # - ./data:/var/lib/postgresql/data
    networks:
      - phx_net

networks:
  phx_net:
    name: phx_net
    driver: bridge
